repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks: [{id: black}]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.5.6
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks: [{id: prettier}]
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v9.9.0
  hooks: [{id: eslint}]
