version: '3.8'

services:
  notes-app:
    build: .
    ports:
      - "3000:80"
    container_name: rob-yyn-notes
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # Development service (optional)
  notes-dev:
    build:
      context: .
      target: builder
    ports:
      - "5173:5173"
    container_name: rob-yyn-notes-dev
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev --host 0.0.0.0
    profiles:
      - dev